services:
  - type: web
    name: interviewiq
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      # Backend env vars
      - key: GROQ_API_KEY
        sync: false
      - key: MONGODB_URL
        sync: false
      - key: MONGODB_DB_NAME
        value: interviewiq
      - key: CLERK_SECRET_KEY
        sync: false
      - key: CLERK_JWT_PUBLIC_KEY
        sync: false
      - key: ELEVENLABS_API_KEY
        sync: false
      - key: ELEVENLABS_VOICE_ID
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: ENVIRONMENT
        value: production
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      # Frontend env vars
      - key: NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
        sync: false
      - key: NEXT_PUBLIC_API_URL
        value: /api
    rootDir: .
    healthCheckPath: /health
